import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import ClientSessionProvider from "../components/ClientSessionProvider";
=======
import ClientSessionProvider from "./components/ClientSessionProvider";
>>>>>>> 3e38e4585f8f968c9345500075b25864d7d916f2

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Booking Room",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en" data-theme="billings">
=======
    <html lang="en">
>>>>>>> 3e38e4585f8f968c9345500075b25864d7d916f2
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientSessionProvider>{children}</ClientSessionProvider>
      </body>
    </html>
  );
}
